# ./backend_SalesDuo/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install  # installs nodemon, tsx, etc.

COPY . .

ENV PATH=/app/node_modules/.bin:$PATH

EXPOSE 5000

CMD ["npm", "run", "dev"]